### PR TITLE
linux.yml: Enable Asan and Ubsan using Clang 13

### PR DESCRIPTION
**Pull request by hartwork**
- https://clang.llvm.org/docs/AddressSanitizer.html
- https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html

### CODE REVIEW

**Comment by gkdr** [comment]
thank you, ii'll take this over one way or another :slightly_smiling_face:

**Comment by hartwork** [comment]
@gkdr my vote for merging as is, and then going after leaks later. Okay?

**Comment by hartwork** [comment]
@gkdr please merge :pray:

**Comment by hartwork** [comment]
@gkdr please please

**Comment by hartwork** [comment]
No action for two years, closing…

**Pull request closed without merging**
