### PR TITLE
fix test compile warnings

### PR DESCRIPTION
**Pull request by gkdr**
edit: autogenerated pr body was for merge against master, which included changes from dev. just confusing so i deleted it.

### CODE REVIEW

**Comment by gkdr** [comment]
guess github actions does its thing on prs too @hartwork :slightly_smiling_face:

**Review by hartwork — APPROVED** [review]
@gkdr so the code is warning free now? Nice! I hope it's okay that I haven't checked how you fixed the warnings in detail. Anything left to do before a merge? I'll rebase my cmake branch on top of the new `dev` right after.

**Comment by gkdr** [comment]
>Anything left to do before a merge? 

don't think so :D

**Comment by hartwork** [comment]
> > Anything left to do before a merge?
> 
> don't think so :D

@gkpr excellent, I have rebased PR #32 onto latest `dev` now.

**Pull request merged**
